### ISSUE TITLE
How can I change the #of participants for each DP-FedAvg

### ISSUE THREAD

**Issue by lovingmage** [ebagdasa/differential-privacy-vs-fairness#1]
Hi,

Just curious which part of the code is for DP-FedAvg, and how can I change modify the #of participants who contribute to the DP-FedAvg. The paper reported C=100, while I'd like to change this value and make some more investigations.

Thanks

**Comment by ebagdasa** [comment]
yeah, sorry, I was using the other repo: https://github.com/ebagdasa/backdoor_federated_learning
